name = "GekkePack"
author = "GekkeWoutie"
version = "v2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5751f21ad29741de4fc0098989f0875ac580f24902dcf6255a3a677e5b9d7f7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
