name = "GekkePack"
author = "GekkeWoutie"
version = "v2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "26fe78494d8f989ee186411ceb172c883b98316fe2790a85e9124e7f40824ec8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
