name = "GekkePack"
author = "GekkeWoutie"
version = "v2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac11f8410f74629b6c98b2f92f12b0ccbadcaa4f64bba2fafc022839ea7453f8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"
